---
abstract: 'Use Pye as a Plack logger'
author:
  - 'Ido Perlmuter <ido@ido50.net>'
build_requires:
  HTTP::Request::Common: 0
  MongoDB: 0
  Plack::Test: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.006, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Plack-Middleware-PyeLogger
requires:
  Carp: 0
  Plack::Middleware: 0
  Plack::Util::Accessor: 0
  Pye: 0
  parent: 0
  perl: 5.006
  strict: 0
  warnings: 0
resources:
  homepage: https://github.com/ido50/Plack-Middleware-PyeLogger
  repository: https://github.com/ido50/Plack-Middleware-PyeLogger.git
version: 1.000000
